### PR TITLE
Add 730 Image, make 530 the default

### PR DESCRIPTION
**Pull request by donporter**
I intended to post the option to make 530 the default image; can separate this if desired.

Main goal is to add a 730 image to the menu, as a non-default.

### CODE REVIEW

**Comment by eric-unc** [comment]
We in 211 may not like having 530 as the default :P

**Comment by donporter** [comment]
If 211 still uses this infrastructure, I'm ok with 530 being non-default.

**Comment by donporter** [comment]
Actually - can I propose the default asks the student to select the course (as in, no default)?  I am sitting here editing Kris's booklet because of this one instruction:
./learncli.sh
to 
./learncli.sh your-course-number

Then each course could use the same instructions.  I prefer not to fork this repo each semester, but also don't want to deal with the fraction of students that miss this detail and have issues using the 211 docker image by accident.

**Comment by eric-unc** [comment]
Honestly I don't see a point in having a bunch of images that are all slightly different but 99.9% the same; we should use one unified image, I don't think there are any conflicts in what we want.

**Comment by KrisJordan** [comment]
I am onboard with a unified, batteries-included mono-image. Since Eric is bringing a head TA voice from 211, I'd say proceed with improving a default image to have what's needed across courses and keep the UX as simple as possible.

**Pull request closed without merging**
